### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ScriptVortexDE** [Razboy20/pterodactyl-ghost#3]
Hey, so it still installs npm but that's it, after 3h also nothing happens anymore 

Can you check your code if everything still works ?

<img width="1695" alt="Bildschirmfoto 2023-03-06 um 22 57 20" src="https://user-images.githubusercontent.com/118630343/223244619-a26e8a9c-c637-47d3-af33-06fffb9e7e5e.png">
<img width="1121" alt="Bildschirmfoto 2023-03-06 um 22 59 57" src="https://user-images.githubusercontent.com/118630343/223244633-20808639-ff5b-468c-b155-327a315d6266.png">

**Comment by Razboy20** [comment]
@Amuria-Codes Sorry for the delay in response, but the egg should install properly now.
